### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Walker-n** [HelloWRC/GrantUiAccess#3]
System.DllNotFoundException: Unable to load DLL 'uiaccess.dll' or one of its dependencies: 找不到指定的模块。 (0x8007007E)
   at GrantUiAccess.Plugin.PrepareForUIAccess()
   at GrantUiAccess.Plugin.Initialize(HostBuilderContext context, IServiceCollection services) in E:\Coding\GrantUiAccess\GrantUiAccess\Plugin.cs:line 18
   at ClassIsland.Services.PluginService.InitializePlugins(HostBuilderContext context, IServiceCollection services) in D:\a\ClassIsland\ClassIsland\ClassIsland\Services\PluginService.cs:line 147

--------------------------------
win11 
（虽然功能正常但是看着闹心(doge)）

**Comment by lcp1234** [comment]
+1：
> System.ComponentModel.Win32Exception (1168): 找不到元素。
   at GrantUiAccess.Plugin.Initialize(HostBuilderContext context, IServiceCollection services) in E:\Coding\GrantUiAccess\GrantUiAccess\Plugin.cs:line 22
   at ClassIsland.Services.PluginService.InitializePlugins(HostBuilderContext context, IServiceCollection services) in D:\a\ClassIsland\ClassIsland\ClassIsland\Services\PluginService.cs:line 151
>

疑似未使用绝对路径所致

**Comment by HelloWRC** [comment]
补全一下 vc 运行库试试看

**Comment by HelloWRC** [comment]
> +1：
> 
> > System.ComponentModel.Win32Exception (1168): 找不到元素。
> > at GrantUiAccess.Plugin.Initialize(HostBuilderContext context, IServiceCollection services) in E:\Coding\GrantUiAccess\GrantUiAccess\Plugin.cs:line 22
> > at ClassIsland.Services.PluginService.InitializePlugins(HostBuilderContext context, IServiceCollection services) in D:\a\ClassIsland\ClassIsland\ClassIsland\Services\PluginService.cs:line 151
> 
> 疑似未使用绝对路径所致

这个错误是因为没有使用管理员身份运行应用导致的，这个插件需要应用以管理员身份运行才能正常工作。

**Comment by lcp1234** [comment]
问题已解决
